# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78226ecc52216482dda47f3abaa4e088390b5d70bfdcc4e8d11f0574ebcf7337887d9421a77cfe748f744cd122faab7ae4156abddca926501360e5a561cc0fd9

test:
  secret_key_base: 7709dda4a5922d1c5ce4fe9aa5075a2493683cf4be1f1acbaa0159c01847312eba2d449f78ca5590ad0bbf4ea3793f553d8d5b52d101647de1e66864a2b8dde3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
